### PR TITLE
Make loglevel configurable through environment variable

### PR DESCRIPTION
**Pull request by peterhoeg**
One could also argue that the default should be `INFO` instead of `DEBUG` but at least now it's configurable.

### CODE REVIEW

**Comment by peterhoeg** [comment]
FWIW, I've been running with this patch for a while now without problems.

**Comment by jacekkow** [comment]
Hi! Sorry for the late reply.

I am not concerned about it breaking anything, but I have strong feelings for command line switch (`--debug` maybe, with change of default log level to INFO?) rather than an environment variable.

Would you try to make such change, preferably using [argparse](https://docs.python.org/3/library/argparse.html)? Or would you prefer me to make this modification?

**Comment by peterhoeg** [comment]
I'm not using this any longer. Do you want me to close this or would you interested in taking it as-is?

**Comment by jacekkow** [comment]
If there is no longer a need for this feature, I'm closing it.

**Pull request closed without merging**
